### ISSUE TITLE
Mention `systemd-socket-activate` as alternative to `systemfd`

### ISSUE THREAD

**Issue by septatrix** [mitsuhiko/listenfd#17]
It is an official tool from systemd which is likely sufficient in many cases and removes the need to install additional packages. It has a few small nuances where it is closer to the systemd behaviour, for better or worse. For example it provides an `--accept` flag to spawn a separate process for each connection, and in general it only starts the process once a connection is really incoming. `systemfd` complements this with a different feature set like availability on Windows. Therefore I think it is beneficial to mention both.

Man page: <https://www.freedesktop.org/software/systemd/man/systemd-socket-activate.html>

**Comment by mitsuhiko** [comment]
Isn't this already mentioned in the README? The whole point of this was to be compatible with systemd :)

**Comment by septatrix** [comment]
It is mentioned that it is intended for the socket activation feature of systemd but I am referring to the `systemd-socket-activate` tool as an alternative to your `systemfd` for _testing_

**Comment by mitsuhiko** [comment]
Resolved in 7d4675c314f65f237f9f5be129129128d3fefc8e
