### ISSUE TITLE
fd 3 is not a socket

### ISSUE THREAD

**Issue by danreeves** [mitsuhiko/listenfd#3]
Hi, with this small reproduction (https://github.com/danreeves/listenfd-bug-repro) I'm always getting the error `fd 3 is not a socket`.

```sh
$ systemfd --no-pid -s http::3000 -- ./target/debug/listenfd-bug
~> socket http://127.0.0.1:3000/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("fd 3 is not a socket") }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Do you have any idea what might be wrong?

```sh
$ systemfd --version
systemfd 0.3.0
$ cargo --version
cargo 1.32.0-nightly (1fa308820 2018-10-31)
$ rustc --version
rustc 1.32.0-nightly (8b096314a 2018-11-02)
```

on the latest macOS

**Comment by danreeves** [comment]
Updating to latest nightly & stable and it works fine on both 🤔 Maybe it was a rustc bug

**Comment by hcgaron** [comment]
> Updating to latest nightly & stable and it works fine on both 🤔 Maybe it was a rustc bug

This randomly started happening in my VSCode integrated terminal this afternoon. Was working fine, then I went for a walk, now won't run at all (same exact error as yours). But my regular terminal (not VSCode integrated) works fine. Very annoying issue. 

I'm on Ubuntu 18.04 I believe (actually ZorinOS, but it's built atop Ubuntu).

**Comment by tv42** [comment]
Successful run:

```
fstat(3, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
```

bad run:

```
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(0x1, 0x9), ...}) = 0
```

I think the bug is on the systemfd side.

```
systemfd --no-pid -s http::3000 -- ls -l /proc/self/fd/3
~> socket http://127.0.0.1:3000/
lr-x------ 1 tv tv 64 May 17 14:26 /proc/self/fd/3 -> /dev/urandom
```

**Comment by tv42** [comment]
Yeah, systemfd is absolutely broken and only works by luck: https://github.com/mitsuhiko/systemfd/issues/4#issuecomment-842621135

**Comment by tv42** [comment]
I'd suggest using https://www.freedesktop.org/software/systemd/man/systemd-socket-activate.html instead of https://github.com/mitsuhiko/systemfd. Tested to work fine.
